### ISSUE TITLE
What to use as Database?

### ISSUE THREAD

**Issue by sunx2** [sunx2/aspiring_youth#2]
### we have

- MYSQL
- SQLITE ( bad for heroku )
- POSTGRESQL ( my choice )
- Others

**Comment by sunx2** [comment]
If you choose Postgres, I can take care of it ezpz

**Comment by sunx2** [comment]
MongoDB sucks

**Comment by sunx2** [comment]
Kueen wants us to use MongoDB and says she will be in charge of it. I am happy with it.

**Comment by raniuday** [comment]
I can deal any sql db
As long as google and stackoverflow got my back

**Comment by sunx2** [comment]
So you want to be in charge of database? we will help you too ofc.

**Comment by sunx2** [comment]
We are selecting MongoDB  ( even tho i hate it ) with in charge  Kueen, @raniuday and @SkyThonk

**Comment by raniuday** [comment]
I have 0 experience in mongo db _shrugs_

**Comment by sunx2** [comment]
Database selected as Postgress
