### ISSUE TITLE
What to use ?

### ISSUE THREAD

**Issue by sunx2** [sunx2/aspiring_youth#6]
DJANGO + DTL + SQLITE3

or

EXPRESS + REACT + MONGO

**Comment by FireFeathers06** [comment]
Django+DTL+SQLite

**Comment by sunx2** [comment]
React with 👍  if you want DJANGO , 👎  for EXPRESS

**Comment by MiKueen** [comment]
We are using React + Django + PostgreSQL + Rest API
_weird combo but ok_

**Comment by sunx2** [comment]
So Our desired and finalized combo is React + Django + Postgress + Django-rest.
I am closing this issue with finalizing details
